name: Ref Duplicate Remover

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install mwparserfromhell requests

      - name: Run bot
        env:
          WIKI_USERNAME: ${{ secrets.WIKI_USER }}
          WIKI_PASSWORD: ${{ secrets.WIKI_PASS }}
        run: python bot.py
